#!/bin/bash

pid_screensaver=0

if [ "$1" = "start" ]
then
	simple-screensaver &
	pid_screensaver=$!
	echo $pid_screensaver > ~/.config/simple-screensaver/pid
elif [ "$1" = "stop" ]
then
	kill $(cat ~/.config/simple-screensaver/pid)
elif [ "$1" = "zeit" ]
then
	echo $2 > ~/.config/simple-screensaver/zeit
fi
